name: Build TWRP

on:
  workflow_dispatch:

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    strategy:
      fail-fast: false
      matrix:
        target: [e2s]

    steps:
      - name: Clone Device Tree
        run: |
          cd ${GITHUB_WORKSPACE}
          git clone https://github.com/scabootssca/android_device_samsung_${{ matrix.target }}.git -b android-12.1 device/samsung/${{ matrix.target }}.git
      #  continue-on-error: true   
      
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12 
      
      - name: Bypass Mkbootimg
        run: |   
          cd ${GITHUB_WORKSPACE}/device/samsung/${{ matrix.target }}
          chmod +x mkbootimg
     #   continue-on-error: true
        
      - name: Building recovery
        run: |
          cd ${GITHUB_WORKSPACE}
          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          lunch twrp_${{ matrix.target }}-eng
          rm -rf .repo/
          make clean
          make recoveryimage -j$(nproc --all)
       # continue-on-error: true  
      
      - name: Set Variables
        run: |
          echo "date=$(TZ=Asia/Bangkok date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT
          echo "Outdir=${GITHUB_WORKSPACE}/out/target/product/${{ matrix.target }}" >> $GITHUB_OUTPUT
        id: var

      - name: Add Img to Tar
        run: |
          cd ${GITHUB_WORKSPACE}/out/target/product/${{ matrix.target }}
          lz4 -B6 --content-size recovery.img recovery.img.lz4
          tar cvf twrp-${{ matrix.target }}-${{ steps.var.outputs.date }}.img.tar recovery.img.lz4
          echo "name=$(find * -name *.tar -type f)" >> $GITHUB_OUTPUT
        id: tarname

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
        with:
           files: ${{ steps.var.outputs.Outdir }}/${{ steps.tarname.outputs.name }}
           name: ${{ steps.tarname.outputs.name }}-${{ github.run_id }}
           tag_name: ${{ github.run_id }}
           body: |
             - None
        env:
           GITHUB_TOKEN: ${{ secrets.TEST }}
          
